# extends:
#   - react-app
#   - ../.eslintrc.yml
# parserOptions:
#   project: ./tsconfig.json
# overrides:
#   - files:
#       - vite.config.ts
#     parserOptions:
#       project: ./tsconfig.node.json

extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project: ./tsconfig.app.json
settings:
  react:
    version: detect
overrides:
  - files:
      - "vite.config.ts"
    parserOptions:
      project: "./tsconfig.node.json"